### ISSUE TITLE
再执行启动之后报错了

### ISSUE THREAD

**Issue by shizeying** [InazumaV/V2bX#23]
报错如下:
```shell
xrayr_1  | V2bX 1.7.2 (A V2board backend based on multi core) 
xrayr_1  | Supported cores: sing, xray
xrayr_1  | This version need V2board version >= 1.7.0.
xrayr_1  | The version have many changed for config, please check your config file
xrayr_1  | time="2023-10-19T13:12:09+08:00" level=panic msg="Failed to understand Routing config  Please check: https://xtls.github.io/config/routing.html" err="infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:netflix > infra/conf: failed to load geosite: NETFLIX > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open geosite.dat: no such file or directory"
xrayr_1  | panic: (*logrus.Entry) 0xc0010fd030
xrayr_1  | 
xrayr_1  | goroutine 1 [running]:
xrayr_1  | github.com/sirupsen/logrus.(*Entry).log(0xc0010fcfc0, 0x0, {0xc000100900, 0x5d})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
xrayr_1  | github.com/sirupsen/logrus.(*Entry).Log(0xc0010fcfc0, 0x0, {0xc000e3f8a0?, 0x3308ae0?, 0xc00013b620?})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
xrayr_1  | github.com/sirupsen/logrus.(*Entry).Panic(...)
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:342
xrayr_1  | github.com/InazumaV/V2bX/core/xray.getCore(0xc00013b1a0)
xrayr_1  |      github.com/InazumaV/V2bX/core/xray/xray.go:92 +0x667
xrayr_1  | github.com/InazumaV/V2bX/core/xray.New(0x2c4d8e0?)
xrayr_1  |      github.com/InazumaV/V2bX/core/xray/xray.go:39 +0x17
xrayr_1  | github.com/InazumaV/V2bX/core.NewCore({0xc0010f9620?, 0x35bc810?, 0xc000e3fc38?})
xrayr_1  |      github.com/InazumaV/V2bX/core/core.go:23 +0x56
xrayr_1  | github.com/InazumaV/V2bX/cmd.serverHandle(0xc0010f0d00?, {0x5e7ac40?, 0x4?, 0x35970b7?})
xrayr_1  |      github.com/InazumaV/V2bX/cmd/server.go:69 +0x299
xrayr_1  | github.com/spf13/cobra.(*Command).execute(0x5e13ca0, {0x5e7ac40, 0x0, 0x0})
xrayr_1  |      github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
xrayr_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x5e14540)
xrayr_1  |      github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
xrayr_1  | github.com/spf13/cobra.(*Command).Execute(...)
xrayr_1  |      github.com/spf13/cobra@v1.7.0/command.go:992
xrayr_1  | github.com/InazumaV/V2bX/cmd.Run()
xrayr_1  |      github.com/InazumaV/V2bX/cmd/cmd.go:15 +0x1a
xrayr_1  | main.main()
xrayr_1  |      github.com/InazumaV/V2bX/main.go:6 +0xf
```
- 这是我 route 配置
```json
{
  "domainStrategy": "rules",
  "rules": [
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "cloudflare-warp",
      "domain": [
        "geosite:netflix",
        "geosite:disney",
        "geosite:openai",
        "domain:openai.com",
        "domain:ai.com",
        "domain:azureedge.net",
        "domain:cdn.auth0.com",
        "domain:sentry.io",
        "domain:intercomcdn.com",
        "domain:intercom.io",
        "domain:google-analytics.com",
        "domain:identrust.com",
        "domain:challenges.cloudflare.com",
        "domain:ingest.sentry.io"
      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "Direct",
      "domain": [



        "geosite:cn"

      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "domain": [
        "geosite:geolocation-!cn",
        "domain:googleapis.cn",
        "domain:gstatic.com",
        "domain:cp.cloudflare.com",
        "dns.google"
      ],
      "outboundTag": "IPv*_out"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "domain": [
        "geosite:geolocation-!cn",
        "domain:googleapis.cn",
        "domain:gstatic.com",
        "domain:cp.cloudflare.com",
        "dns.google"
      ],
      "outboundTag": "IPv*_out"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "IP*_out",
      "network": "udp,tcp"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "blocked",
      "protocol": [
        "bittorrent"
      ],
      "ip": [
      
      ],
      "domain": [
        "geosite:category-ads-all"
      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "Reject",
      "domain": [
       "geosite:category-ads-all",
      "geosite:category-porn"
      ]
    }
  ]
}
```
- 这是我的 config.json的配置
```json
{
  "domainStrategy": "rules",
  "rules": [
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "cloudflare-warp",
      "domain": [
        "geosite:netflix",
        "geosite:disney",
        "geosite:openai",
        "domain:openai.com",
        "domain:ai.com",
        "domain:azureedge.net",
        "domain:cdn.auth0.com",
        "domain:sentry.io",
        "domain:intercomcdn.com",
        "domain:intercom.io",
        "domain:google-analytics.com",
        "domain:identrust.com",
        "domain:challenges.cloudflare.com",
        "domain:ingest.sentry.io"
      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "Direct",
      "domain": [



        "geosite:cn"

      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "domain": [
        "geosite:geolocation-!cn",
        "domain:googleapis.cn",
        "domain:gstatic.com",
        "domain:cp.cloudflare.com",
        "dns.google"
      ],
      "outboundTag": "IPv*_out"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "domain": [
        "geosite:geolocation-!cn",
        "domain:googleapis.cn",
        "domain:gstatic.com",
        "domain:cp.cloudflare.com",
        "dns.google"
      ],
      "outboundTag": "IPv*_out"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "IP*_out",
      "network": "udp,tcp"
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "blocked",
      "protocol": [
        "bittorrent"
      ],
      "ip": [
      
      ],
      "domain": [
        "geosite:category-ads-all"
      ]
    },
    {
      "type": "field",
"domainMatcher": "hybrid",
      "outboundTag": "Reject",
      "domain": [
       "geosite:category-ads-all",
      "geosite:category-porn"
      ]
    }
  ]
}
[root@host-by config]# cat config.json 
{
    "Log": {
    "Level": "error",
    "Output": ""
  },
  "Cores": [
    {
      "Type": "xray",
      "Log": {
        // 同 Xray-core log 部分配置

        "Level": "error"
      },
      // 静态资源文件目录
      "AssetPath": "",
      // DNS配置文件目录
      "DnsConfigPath": "/etc/V2bX/dns.json",
      // 路由配置文件目录
      "RouteConfigPath": "/etc/V2bX/route.json",
      // 本地策略相关配置
      "ConnectionConfig": {
        // 详见 https://xtls.github.io/config/policy.html#levelpolicyobject

        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 2,
        "downlinkOnly": 5,
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "bufferSize": 4
      },
      // Inbound配置文件目录
     "InboundConfigPath": "/etc/V2bX/custom_inbound.json",
      // Outbound配置文件目录
      "OutboundConfigPath": "/etc/V2bX/custom_outbound.json"
    }
  ],
  "ApiHost": "",
  "ApiKey": "",
  "NodeID": 1,
  "NodeType": "trojan",
  "Timeout": 30,
  "ListenIP": "0.0.0.0",
  "SendIP": "0.0.0.0",
  "EnableProxyProtocol": false,
  "EnableTFO": true,
  "DNSType": "UseIP",
      // 证书相关配置
      "CertConfig": {
        // 证书申请模式，none、http、dns、self
        "CertMode": "tls",

        "RejectUnknownSni": true,

        // 证书域名
        "CertDomain": "",

        // 证书文件目录
        "CertFile": "/etc/V2bX/cert/ss.cert",

        // 密钥文件目录
        "KeyFile": "/etc/V2bX/cert/ss.key",

        // 申请证书时使用的用户邮箱
        "Email": "w",

        // DNS解析提供者
        "Provider": "cloudflare",

        // DNS解析提供者的环境变量，详见 https://go-acme.github.io/lego/dns/
        "DNSEnv": {
          "CLOUDFLARE_EMAIL": "w",
          "CLOUDFLARE_API_KEY": ""
        }
      }
}
```

**Comment by Yuzuki616** [comment]
字面意思，geosite.dat不存在

**Comment by shizeying** [comment]
但是我其实存在的，都在同一个文件夹下发自我的 iPhone在 2023年10月19日，13:22，Yuzuki ***@***.***> 写道：﻿
字面意思，geosite.dat不存在

**Comment by shizeying** [comment]
我这里的再同一个目录下的
[root@host-by config]# ls
config.json  config.yml  custom_inbound.json  custom_outbound.json  dns.json  geoip.dat  geosite.dat  infra  route.json  rulelist  XrayR
[root@host-by config]#
